<?
use PKMVC\BaseElement;
?>
<?  if (!empty($idx) && ($idx == '__template__')) { ?>
  <div class='form-template' data-item-template="
       <?=BaseElement::clean(
"<div class='base-item-el'>
  $item_data
  <div class='button delete-item-button'>Delete Item?</div>
</div>"
               );
?>"></div>
<? } else { ?>
<div class='base-item-el'>
  <?=$item_data?>
  <div class='button delete-item-button'>Delete Item?</div>
</div>
<? } ?>