<!--
  Default Menu Template for PKMVC Framework
 * PKMVC Framework 
 *
 * @author    Paul Kirkaas
 * @email     p.kirkaas@gmail.com
 * @link     
 * @copyright Copyright (c) 2012-2014 Paul Kirkaas. All rights Reserved
 * @license   http://opensource.org/licenses/BSD-3-Clause  
-->

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"> <img src="/img/dumbGraphic.png" alt="Quantum Profiles"/>Quantum Profiles</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <?php foreach ($menu_items as $menu_item) { #Menu Item array ?>
          <li class="<?= static::activeRoute($menu_item['route']) ?>">
            <a href="<?= static::makeUrl($menu_item['route']) ?>" title='<?= $menu_item['title'] ?>'><?= $menu_item['label'] ?></a></li>

        <?php } ?>
          <? if (!empty($handle)) echo "<li class='proud'>Welcome, $handle</li>"; ?>
      </ul>
      <div class="form-in-menu">
      </div>
    </div><!--/.nav-collapse -->



    <? # Start: Here are the nav bar items and conditionals....  ?>


  </div>
</nav>
