<?
namespace PKMVC;
?>
<!DOCTYPE html>
<html>

<head>

<meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
<? static::addCss('/css/bootstrap.min.css'); ?>
<? static::addCss('/css/bootstrap.min.css'); ?>
<? static::addCss('/css/ui-lightness/jquery-ui-1.10.4.custom.min.css'); ?>
<? static::addJs('/js/jquery-1.11.1.min.js'); ?>
<? static::addJs('/js/jquery-ui-1.10.4.custom.min.js'); ?>
<? static::addJs('/js/bootstrap.min.js'); ?>

<?=static::getCss();?>

<link type='text/css' rel='stylesheet' href='MyStyleSheet.css'/>
<title>The PKMVC Demo App</title>
</head>
<body>
<div class='main-body'>
<? $class = get_class(); ?>
<h3>THIS CLASS IS::: [<?=$class?>]</h3>
<?#pkdebug("Slot:", BaseController::$slots);?>
<?=BaseController::getSlot('top-menu')?>
<h1>This is the Layout!</h1>

<div class='main-content'>
<?=$content?>
</div> <!-- close div main-content -->

</div> <!-- close div main-body -->
<?=static::getJs();?>
</body>
</html>

